### ISSUE TITLE
Developer Onboarding Checklist for Nick Dowmon

### ISSUE THREAD

**Issue by ndowmon** [ndowmon/issue-template-test#2]
## Developer New Hire Checklist

A helpful checklist to manage completion of [developer onboarding](https://github.com/JupiterOne/wiki/blob/master/developer-onboarding.md).

### Pre-requisites:

- [x] You have been added to Google for Single Sign-On (SSO) and you are configured with developer role.
- [x] You have access to your `firstname.lastname@jupiterone.com` email account.
- [x] You have access to [JupiterOne Slack workspace](https://jptrone.slack.com/).
- [x] You have installed a 2-factor authentication app on your device

---

### User Access

- [x] Download Slack and login to workspaces:
    - JupiterOne Organization: <https://jptrone.slack.com>. Join the following channels, plus any other public channels that seem appealing to you:
        - `#dev`
        - `#dev-backend`, `#dev-frontend`, or `#dev-integrations`, depending on team.
        - `#dev-tips`
        - `#general`
        - `#status`
    - JupiterOne Community: <https://jupiterone-community.slack.com>
- [x] Activate JupiterOne Endpoint Compliance Agent
- [x] Verfiy access & bookmark Google SSO Dashboard: <https://workspace.google.com/dashboard>. Verify the following apps through Google SSO:
    - Mail: <https://mail.google.com>
    - Calendar: <https://calendar.google.com>
    - AWS: Access by clicking the "AWS" app in the Google SSO Dashboard.
    - Azure DevOps: <https://dev.azure.com/jupiterone>// TODO: HOW TO ACCESS?
- [x] Sign in to (or create) npm account: <https://www.npmjs.com/>
- [x] Sign in to (or create) github account: <https://github.com>
- [x] Get access to the JupiterOne Application by posting a message in `#security` asking for access to JupiterOne (<https://j1.apps.us.jupiterone.io>). In the `policies` app, review and accept the policy information.
- [x] Get access to JupiterOne Organization accounts:
    - NPM <https://www.npmjs.com/org/jupiterone>: send a message to `#security` slack channel with your NPM username
    - Github <https://github.com/jupiterone>: send a message to `#security` slack channel with your github username
    - Bitbucket <https://bitbucket.org/jupiterone>: send a message to `#security` slack channel to be added to bitbucket via Google SSO
- [x] Generate SSH key and add it to your user profiles in 
    - Github: <https://github.com/settings/keys>
    - Bitbucket: <https://bitbucket.org/account/settings/ssh-keys>
- [ ] Add a profile picture to your accounts. Use a representative photograph head shot instead of an artistic
    avatar. Add to all accounts, including:
    - Slack
    - Bitbucket
    - Github
    - NPM
    - Motivosity: <https://app.motivosity.com/home/index.xhtml>
    - Justworks: <https://secure.justworks.com/dashboard>
    - CultureAmp: <https://jupiterone.cultureamp.com/performance>

### Software Installation

- [ ] Install your editor / terminal of choice (VSCode / iterm2)
- [ ] (OPTIONAL, MAC USERS ONLY): Install Homebrew: <https://brew.sh>
- [ ] Install the AWS CLI: <https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html>
- [ ] Install Docker: <https://docs.docker.com/get-docker>
- [ ] Install Node Version Manager: <https://github.com/creationix/nvm#install-script>
- [ ] Install latest `node` via `nvm install node`
- [ ] Install Yarn package manager: <https://yarnpkg.com/getting-started/install>

### System Configuration

- [ ] Set up VPN:
    1. `git clone git@bitbucket.org:jupiterone/pritunl-web-access.git`

    1. `cd pritunl-web-access && yarn && yarn get-vpn-access --profile jupiterone-infra`
       (subsitute 'jupiterone-dev' for the Dev VPN)

    1. Head over to the #security-audit channel in Slack. Click the link
       generated by your action in step 2.
    
### Further Reading

- [ ] Skim and bookmark the JupiterOne Development Guide (<https://github.com/JupiterOne/wiki/blob/master/development-guide.md>) for future reference.
- [ ] Join the `#status` channel
- [ ] (OPTIONAL) Open and complete **Developer Onboarding Checklist - <Backend/Frontend/Integrations> Team**, if applicable for your team.
